# Author: Galal Abdelaziz
# File Name:weather-data.yml

name: Weather Data Workflow

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write 
  
jobs:
  fetch_weather_data:
    runs-on: ubuntu-latest


