# Author: Galal Abdelaziz
# File Name:weather-data.yml

name: Daily Weather Data Update

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Allow write access to the repository contents

jobs:
  update_weather_data:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clones the repository using the latest version

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Run weather script
        run: |
          chmod +x weather.sh  # Ensure the script has execute permissions
          if ! ./weather.sh; then
            echo "Weather script failed"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .  # Add all changes in the repository
          git commit -m "Update weather data" || echo "No changes to commit"  # Commit changes
          git push origin main  # Push changes back to the main branch
